### ISSUE TITLE
filter dialog reset button has no effect (Version 0.2.17)

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#56] opened 2023-08-17 17:58 UTC
Currently, the filter dialog reset button seems to have no effect.

steps to reproduce: (note multiple ways to do this).
1.
- open the filter dialog, select synoptic layer.
- select a date on the calendar control.
- hit the reset button, note that nothing happens.

2.
- open the filter dialog, select synoptic layer.
- hit the search button, note there is data retrieved.
- hit the reset button, note that nothing happens.

The expected behavior of the reset button is to clear all filter selections and previous results.

**Comment by lstillwe** [comment] 2023-08-25 21:26
This is a duplicate of #29 - I will added these comments to that one

**Closed as completed by lstillwe** 2023-08-25 21:26 UTC
