### ISSUE TITLE
Confusing messaging

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#84] opened 2023-10-09 20:25 UTC
are 3 or 0 selected? could use some better titles of what the data represents here.
![image](https://github.com/RENCI/TerriaMap/assets/19691521/e22c83a4-b45e-481d-9b61-19ea6e85f91d)

**Comment by scrummish** [comment] 2023-10-17 18:46
closing as duplicate of #87

**Closed as completed by scrummish** 2023-10-17 18:46 UTC
